spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1105
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.example.blog: info
  file:
    name: log/blog-pro.log
server:
  port: 8081

